name: Rapier CI bench

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:

jobs:
  send-bench-message:
    env:
      BENCHBOT_AMQP_USER: ${{ secrets.BENCHBOT_AMQP_USER }}
      BENCHBOT_AMQP_PASS: ${{ secrets.BENCHBOT_AMQP_PASS }}
      BENCHBOT_AMQP_VHOST: ${{ secrets.BENCHBOT_AMQP_VHOST }}
      BENCHBOT_AMQP_HOST: ${{ secrets.BENCHBOT_AMQP_HOST }}
      BENCHBOT_TARGET_REPO: ${{ github.github.pull_request.head.clone_url }}
      BENCHBOT_TARGET_COMMIT: ${{ github.event.pull_request.head.sha }}
      BENCHBOT_SHA: ${{ github.sha }}
      BENCHBOT_HEAD_REF: ${{github.head_ref}}
      BENCHBOT_OTHER_BACKENDS: false
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Find commit SHA
        if: github.head_ref == ''
        run: |
          echo "BENCHBOT_TARGET_COMMIT=$BENCHBOT_SHA" >> $GITHUB_ENV
          echo "BENCHBOT_HEAD_REF=master" >> $GITHUB_ENV
          echo "BENCHBOT_OTHER_BACKENDS=true" >> $GITHUB_ENV
      - name: Send 3D bench message
        shell: bash
        run: |
          echo '{"properties":{},"routing_key":"benchmark","payload":"{ \"repository\":\"'$BENCHBOT_TARGET_REPO'\", \"branch\":\"'BENCHBOT_HEAD_REF'\", \"commit\":\"'$BENCHBOT_TARGET_COMMIT'\", \"other_backends\":'$BENCHBOT_OTHER_BACKENDS' }","payload_encoding":"string"}'